Dora artifacts
kscalelabs/sim pull request #54
Opened 2024-08-14 22:25 UTC by wuallenwu

2024-08-15 18:33 UTC, budzianowski requested changes

2024-08-15 18:33 UTC, budzianowski commented on sim/humanoid_gym/envs/dora_config.py
> +        decimation = 4  # 100hz
Please change to 10

2024-08-15 18:33 UTC, budzianowski commented on sim/humanoid_gym/envs/dora_env.py
> +        left_yaw_roll = joint_diff[:, :2]
Please fix this.

2024-08-16 05:45 UTC, wuallenwu commented on sim/humanoid_gym/envs/dora_config.py
> +        decimation = 4  # 100hz
fixed

2024-08-16 05:45 UTC, wuallenwu commented on sim/humanoid_gym/envs/dora_env.py
> +        left_yaw_roll = joint_diff[:, :2]
fixed

2024-08-16 05:51 UTC, budzianowski approved these changes

2024-08-16 05:51 UTC, budzianowski commented on sim/humanoid_gym/envs/dora_config.py
> +        name = "stompy"
dora

2024-08-16 06:36 UTC, merged